// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/cilium/api/v1/models"
)

// GetPodAnnotationsOKCode is the HTTP code returned for type GetPodAnnotationsOK
const GetPodAnnotationsOKCode int = 200

/*
GetPodAnnotationsOK Success

swagger:response getPodAnnotationsOK
*/
type GetPodAnnotationsOK struct {

	/*
	  In: Body
	*/
	Payload *models.PodAnnotationsReply `json:"body,omitempty"`
}

// NewGetPodAnnotationsOK creates GetPodAnnotationsOK with default headers values
func NewGetPodAnnotationsOK() *GetPodAnnotationsOK {

	return &GetPodAnnotationsOK{}
}

// WithPayload adds the payload to the get pod annotations o k response
func (o *GetPodAnnotationsOK) WithPayload(payload *models.PodAnnotationsReply) *GetPodAnnotationsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get pod annotations o k response
func (o *GetPodAnnotationsOK) SetPayload(payload *models.PodAnnotationsReply) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPodAnnotationsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPodAnnotationsBadRequestCode is the HTTP code returned for type GetPodAnnotationsBadRequest
const GetPodAnnotationsBadRequestCode int = 400

/*
GetPodAnnotationsBadRequest Invalid request

swagger:response getPodAnnotationsBadRequest
*/
type GetPodAnnotationsBadRequest struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewGetPodAnnotationsBadRequest creates GetPodAnnotationsBadRequest with default headers values
func NewGetPodAnnotationsBadRequest() *GetPodAnnotationsBadRequest {

	return &GetPodAnnotationsBadRequest{}
}

// WithPayload adds the payload to the get pod annotations bad request response
func (o *GetPodAnnotationsBadRequest) WithPayload(payload models.Error) *GetPodAnnotationsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get pod annotations bad request response
func (o *GetPodAnnotationsBadRequest) SetPayload(payload models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPodAnnotationsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetPodAnnotationsNotFoundCode is the HTTP code returned for type GetPodAnnotationsNotFound
const GetPodAnnotationsNotFoundCode int = 404

/*
GetPodAnnotationsNotFound No such pod was found

swagger:response getPodAnnotationsNotFound
*/
type GetPodAnnotationsNotFound struct {
}

// NewGetPodAnnotationsNotFound creates GetPodAnnotationsNotFound with default headers values
func NewGetPodAnnotationsNotFound() *GetPodAnnotationsNotFound {

	return &GetPodAnnotationsNotFound{}
}

// WriteResponse to the client
func (o *GetPodAnnotationsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
