// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPodAnnotationsHandlerFunc turns a function with the right signature into a get pod annotations handler
type GetPodAnnotationsHandlerFunc func(GetPodAnnotationsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPodAnnotationsHandlerFunc) Handle(params GetPodAnnotationsParams) middleware.Responder {
	return fn(params)
}

// GetPodAnnotationsHandler interface for that can handle valid get pod annotations params
type GetPodAnnotationsHandler interface {
	Handle(GetPodAnnotationsParams) middleware.Responder
}

// NewGetPodAnnotations creates a new http.Handler for the get pod annotations operation
func NewGetPodAnnotations(ctx *middleware.Context, handler GetPodAnnotationsHandler) *GetPodAnnotations {
	return &GetPodAnnotations{Context: ctx, Handler: handler}
}

/*
	GetPodAnnotations swagger:route GET /pod_annotations daemon getPodAnnotations

Lists cilium-specific annotations for a pod.

Retrieves cilium-specific annotations for a pod.
*/
type GetPodAnnotations struct {
	Context *middleware.Context
	Handler GetPodAnnotationsHandler
}

func (o *GetPodAnnotations) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPodAnnotationsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
