// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetPodAnnotationsParams creates a new GetPodAnnotationsParams object
//
// There are no default values defined in the spec.
func NewGetPodAnnotationsParams() GetPodAnnotationsParams {

	return GetPodAnnotationsParams{}
}

// GetPodAnnotationsParams contains all the bound params for the get pod annotations operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetPodAnnotations
type GetPodAnnotationsParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*k8s namespace
	  Required: true
	  In: query
	*/
	Namespace string

	/*k8s pod name
	  Required: true
	  In: query
	*/
	Pod string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetPodAnnotationsParams() beforehand.
func (o *GetPodAnnotationsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r
	qs := runtime.Values(r.URL.Query())

	qNamespace, qhkNamespace, _ := qs.GetOK("namespace")
	if err := o.bindNamespace(qNamespace, qhkNamespace, route.Formats); err != nil {
		res = append(res, err)
	}

	qPod, qhkPod, _ := qs.GetOK("pod")
	if err := o.bindPod(qPod, qhkPod, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindNamespace binds and validates parameter Namespace from query.
func (o *GetPodAnnotationsParams) bindNamespace(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("namespace", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("namespace", "query", raw); err != nil {
		return err
	}
	o.Namespace = raw

	return nil
}

// bindPod binds and validates parameter Pod from query.
func (o *GetPodAnnotationsParams) bindPod(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("pod", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("pod", "query", raw); err != nil {
		return err
	}
	o.Pod = raw

	return nil
}
