// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/cilium/api/v1/models"
)

// GetPodAnnotationsReader is a Reader for the GetPodAnnotations structure.
type GetPodAnnotationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPodAnnotationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetPodAnnotationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetPodAnnotationsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetPodAnnotationsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /pod_annotations] GetPodAnnotations", response, response.Code())
	}
}

// NewGetPodAnnotationsOK creates a GetPodAnnotationsOK with default headers values
func NewGetPodAnnotationsOK() *GetPodAnnotationsOK {
	return &GetPodAnnotationsOK{}
}

/*
GetPodAnnotationsOK describes a response with status code 200, with default header values.

Success
*/
type GetPodAnnotationsOK struct {
	Payload *models.PodAnnotationsReply
}

// IsSuccess returns true when this get pod annotations o k response has a 2xx status code
func (o *GetPodAnnotationsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get pod annotations o k response has a 3xx status code
func (o *GetPodAnnotationsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get pod annotations o k response has a 4xx status code
func (o *GetPodAnnotationsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get pod annotations o k response has a 5xx status code
func (o *GetPodAnnotationsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get pod annotations o k response a status code equal to that given
func (o *GetPodAnnotationsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get pod annotations o k response
func (o *GetPodAnnotationsOK) Code() int {
	return 200
}

func (o *GetPodAnnotationsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pod_annotations][%d] getPodAnnotationsOK %s", 200, payload)
}

func (o *GetPodAnnotationsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pod_annotations][%d] getPodAnnotationsOK %s", 200, payload)
}

func (o *GetPodAnnotationsOK) GetPayload() *models.PodAnnotationsReply {
	return o.Payload
}

func (o *GetPodAnnotationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PodAnnotationsReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetPodAnnotationsBadRequest creates a GetPodAnnotationsBadRequest with default headers values
func NewGetPodAnnotationsBadRequest() *GetPodAnnotationsBadRequest {
	return &GetPodAnnotationsBadRequest{}
}

/*
GetPodAnnotationsBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type GetPodAnnotationsBadRequest struct {
	Payload models.Error
}

// IsSuccess returns true when this get pod annotations bad request response has a 2xx status code
func (o *GetPodAnnotationsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get pod annotations bad request response has a 3xx status code
func (o *GetPodAnnotationsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get pod annotations bad request response has a 4xx status code
func (o *GetPodAnnotationsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get pod annotations bad request response has a 5xx status code
func (o *GetPodAnnotationsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get pod annotations bad request response a status code equal to that given
func (o *GetPodAnnotationsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get pod annotations bad request response
func (o *GetPodAnnotationsBadRequest) Code() int {
	return 400
}

func (o *GetPodAnnotationsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pod_annotations][%d] getPodAnnotationsBadRequest %s", 400, payload)
}

func (o *GetPodAnnotationsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pod_annotations][%d] getPodAnnotationsBadRequest %s", 400, payload)
}

func (o *GetPodAnnotationsBadRequest) GetPayload() models.Error {
	return o.Payload
}

func (o *GetPodAnnotationsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetPodAnnotationsNotFound creates a GetPodAnnotationsNotFound with default headers values
func NewGetPodAnnotationsNotFound() *GetPodAnnotationsNotFound {
	return &GetPodAnnotationsNotFound{}
}

/*
GetPodAnnotationsNotFound describes a response with status code 404, with default header values.

No such pod was found
*/
type GetPodAnnotationsNotFound struct {
}

// IsSuccess returns true when this get pod annotations not found response has a 2xx status code
func (o *GetPodAnnotationsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get pod annotations not found response has a 3xx status code
func (o *GetPodAnnotationsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get pod annotations not found response has a 4xx status code
func (o *GetPodAnnotationsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get pod annotations not found response has a 5xx status code
func (o *GetPodAnnotationsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get pod annotations not found response a status code equal to that given
func (o *GetPodAnnotationsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get pod annotations not found response
func (o *GetPodAnnotationsNotFound) Code() int {
	return 404
}

func (o *GetPodAnnotationsNotFound) Error() string {
	return fmt.Sprintf("[GET /pod_annotations][%d] getPodAnnotationsNotFound", 404)
}

func (o *GetPodAnnotationsNotFound) String() string {
	return fmt.Sprintf("[GET /pod_annotations][%d] getPodAnnotationsNotFound", 404)
}

func (o *GetPodAnnotationsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
