// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPodAnnotationsParams creates a new GetPodAnnotationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPodAnnotationsParams() *GetPodAnnotationsParams {
	return &GetPodAnnotationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPodAnnotationsParamsWithTimeout creates a new GetPodAnnotationsParams object
// with the ability to set a timeout on a request.
func NewGetPodAnnotationsParamsWithTimeout(timeout time.Duration) *GetPodAnnotationsParams {
	return &GetPodAnnotationsParams{
		timeout: timeout,
	}
}

// NewGetPodAnnotationsParamsWithContext creates a new GetPodAnnotationsParams object
// with the ability to set a context for a request.
func NewGetPodAnnotationsParamsWithContext(ctx context.Context) *GetPodAnnotationsParams {
	return &GetPodAnnotationsParams{
		Context: ctx,
	}
}

// NewGetPodAnnotationsParamsWithHTTPClient creates a new GetPodAnnotationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPodAnnotationsParamsWithHTTPClient(client *http.Client) *GetPodAnnotationsParams {
	return &GetPodAnnotationsParams{
		HTTPClient: client,
	}
}

/*
GetPodAnnotationsParams contains all the parameters to send to the API endpoint

	for the get pod annotations operation.

	Typically these are written to a http.Request.
*/
type GetPodAnnotationsParams struct {

	/* Namespace.

	   k8s namespace
	*/
	Namespace string

	/* Pod.

	   k8s pod name
	*/
	Pod string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get pod annotations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPodAnnotationsParams) WithDefaults() *GetPodAnnotationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get pod annotations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPodAnnotationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get pod annotations params
func (o *GetPodAnnotationsParams) WithTimeout(timeout time.Duration) *GetPodAnnotationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get pod annotations params
func (o *GetPodAnnotationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get pod annotations params
func (o *GetPodAnnotationsParams) WithContext(ctx context.Context) *GetPodAnnotationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get pod annotations params
func (o *GetPodAnnotationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get pod annotations params
func (o *GetPodAnnotationsParams) WithHTTPClient(client *http.Client) *GetPodAnnotationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get pod annotations params
func (o *GetPodAnnotationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamespace adds the namespace to the get pod annotations params
func (o *GetPodAnnotationsParams) WithNamespace(namespace string) *GetPodAnnotationsParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the get pod annotations params
func (o *GetPodAnnotationsParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithPod adds the pod to the get pod annotations params
func (o *GetPodAnnotationsParams) WithPod(pod string) *GetPodAnnotationsParams {
	o.SetPod(pod)
	return o
}

// SetPod adds the pod to the get pod annotations params
func (o *GetPodAnnotationsParams) SetPod(pod string) {
	o.Pod = pod
}

// WriteToRequest writes these params to a swagger request
func (o *GetPodAnnotationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param namespace
	qrNamespace := o.Namespace
	qNamespace := qrNamespace
	if qNamespace != "" {

		if err := r.SetQueryParam("namespace", qNamespace); err != nil {
			return err
		}
	}

	// query param pod
	qrPod := o.Pod
	qPod := qrPod
	if qPod != "" {

		if err := r.SetQueryParam("pod", qPod); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
